/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem;

/**
 *
 * @author owner
 */
public class ExamDepartment extends javax.swing.JFrame {

    /**
     * Creates new form ExamDepartment
     */
    public ExamDepartment() {
        initComponents();
        
        hidepanels();
    }
    
    final public void hidepanels(){
        jpnewmarks.setVisible(false);
        jpresults.setVisible(false);
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jpnewmarks = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jpresults = new javax.swing.JPanel();
        jpstudentmarks = new javax.swing.JPanel();
        jpclassanalysis = new javax.swing.JPanel();
        jpsubjectanalysis = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmnewmarks = new javax.swing.JMenuItem();
        jmresults = new javax.swing.JMenuItem();
        jmstudenmarks = new javax.swing.JMenuItem();
        jmlogout = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmclassanalysis = new javax.swing.JMenuItem();
        jmsubjectanalysis = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 600));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1150, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 600));
        jPanel1.setLayout(null);

        jpnewmarks.setBackground(new java.awt.Color(255, 255, 255));
        jpnewmarks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "New Marks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpnewmarks.setMinimumSize(new java.awt.Dimension(1130, 570));
        jpnewmarks.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel1.setText("Add Year  :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(11, 21, 70, 14);

        jTextField1.setColumns(4);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1);
        jTextField1.setBounds(80, 20, 120, 20);

        jLabel2.setText("Class  :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 60, 60, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel2.add(jComboBox1);
        jComboBox1.setBounds(80, 60, 120, 20);

        jLabel3.setText("Term :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(300, 20, 50, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel2.add(jComboBox2);
        jComboBox2.setBounds(370, 20, 130, 20);

        jLabel4.setText("Exam Module  :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(260, 60, 90, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Series 1", "Series 2", "Series 3", "Series 4" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox3);
        jComboBox3.setBounds(370, 60, 130, 20);

        jpnewmarks.add(jPanel2);
        jPanel2.setBounds(6, 16, 1100, 100);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jpnewmarks.add(jScrollPane1);
        jScrollPane1.setBounds(12, 140, 1090, 410);

        jPanel1.add(jpnewmarks);
        jpnewmarks.setBounds(10, 20, 1130, 570);

        jpresults.setBackground(new java.awt.Color(255, 255, 255));
        jpresults.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N

        javax.swing.GroupLayout jpresultsLayout = new javax.swing.GroupLayout(jpresults);
        jpresults.setLayout(jpresultsLayout);
        jpresultsLayout.setHorizontalGroup(
            jpresultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 768, Short.MAX_VALUE)
        );
        jpresultsLayout.setVerticalGroup(
            jpresultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );

        jPanel1.add(jpresults);
        jpresults.setBounds(10, 20, 780, 210);

        jpstudentmarks.setBackground(new java.awt.Color(255, 255, 255));
        jpstudentmarks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Student Marks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N

        javax.swing.GroupLayout jpstudentmarksLayout = new javax.swing.GroupLayout(jpstudentmarks);
        jpstudentmarks.setLayout(jpstudentmarksLayout);
        jpstudentmarksLayout.setHorizontalGroup(
            jpstudentmarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 828, Short.MAX_VALUE)
        );
        jpstudentmarksLayout.setVerticalGroup(
            jpstudentmarksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );

        jPanel1.add(jpstudentmarks);
        jpstudentmarks.setBounds(10, 20, 840, 180);

        jpclassanalysis.setBackground(new java.awt.Color(255, 255, 255));
        jpclassanalysis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Class Analysis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N

        javax.swing.GroupLayout jpclassanalysisLayout = new javax.swing.GroupLayout(jpclassanalysis);
        jpclassanalysis.setLayout(jpclassanalysisLayout);
        jpclassanalysisLayout.setHorizontalGroup(
            jpclassanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        jpclassanalysisLayout.setVerticalGroup(
            jpclassanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jPanel1.add(jpclassanalysis);
        jpclassanalysis.setBounds(10, 20, 900, 150);

        jpsubjectanalysis.setBackground(new java.awt.Color(255, 255, 255));
        jpsubjectanalysis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Subject Analysis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N

        javax.swing.GroupLayout jpsubjectanalysisLayout = new javax.swing.GroupLayout(jpsubjectanalysis);
        jpsubjectanalysis.setLayout(jpsubjectanalysisLayout);
        jpsubjectanalysisLayout.setHorizontalGroup(
            jpsubjectanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 958, Short.MAX_VALUE)
        );
        jpsubjectanalysisLayout.setVerticalGroup(
            jpsubjectanalysisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 78, Short.MAX_VALUE)
        );

        jPanel1.add(jpsubjectanalysis);
        jpsubjectanalysis.setBounds(10, 20, 970, 100);

        jMenu2.setText("Action");

        jmnewmarks.setText("New Marks");
        jmnewmarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnewmarksMouseClicked(evt);
            }
        });
        jmnewmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnewmarksActionPerformed(evt);
            }
        });
        jMenu2.add(jmnewmarks);

        jmresults.setText("Results");
        jmresults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmresultsMouseClicked(evt);
            }
        });
        jmresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmresultsActionPerformed(evt);
            }
        });
        jMenu2.add(jmresults);

        jmstudenmarks.setText("Sutent Marks");
        jmstudenmarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmstudenmarksMouseClicked(evt);
            }
        });
        jmstudenmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmstudenmarksActionPerformed(evt);
            }
        });
        jMenu2.add(jmstudenmarks);

        jmlogout.setText("Logout");
        jmlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmlogoutMouseClicked(evt);
            }
        });
        jmlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlogoutActionPerformed(evt);
            }
        });
        jMenu2.add(jmlogout);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Analytics");

        jmclassanalysis.setText("Class Analysis");
        jmclassanalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmclassanalysisMouseClicked(evt);
            }
        });
        jmclassanalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmclassanalysisActionPerformed(evt);
            }
        });
        jMenu3.add(jmclassanalysis);

        jmsubjectanalysis.setText("Subject Analysis");
        jmsubjectanalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmsubjectanalysisMouseClicked(evt);
            }
        });
        jmsubjectanalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsubjectanalysisActionPerformed(evt);
            }
        });
        jMenu3.add(jmsubjectanalysis);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmnewmarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnewmarksMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jmnewmarksMouseClicked

    private void jmresultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmresultsMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jmresultsMouseClicked

    private void jmstudenmarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmstudenmarksMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jmstudenmarksMouseClicked

    private void jmlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmlogoutMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmlogoutMouseClicked

    private void jmclassanalysisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmclassanalysisMouseClicked
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_jmclassanalysisMouseClicked

    private void jmsubjectanalysisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmsubjectanalysisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmsubjectanalysisMouseClicked

    private void jmsubjectanalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsubjectanalysisActionPerformed
        // TODO add your handling code here:
        jpnewmarks.setVisible(false);
        jpresults.setVisible(false);
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(true);
    }//GEN-LAST:event_jmsubjectanalysisActionPerformed

    private void jmclassanalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmclassanalysisActionPerformed
        // TODO add your handling code here:
           jpsubjectanalysis.setVisible(false);
        jpnewmarks.setVisible(false);
        jpresults.setVisible(false);
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(true);
    }//GEN-LAST:event_jmclassanalysisActionPerformed

    private void jmlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginAccounts().setVisible(true);
    }//GEN-LAST:event_jmlogoutActionPerformed

    private void jmstudenmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmstudenmarksActionPerformed
        // TODO add your handling code here:
         jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(false);
        jpnewmarks.setVisible(false);
        jpresults.setVisible(false);
        jpstudentmarks.setVisible(true);
    }//GEN-LAST:event_jmstudenmarksActionPerformed

    private void jmresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmresultsActionPerformed
        // TODO add your handling code here:
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(false);
        jpnewmarks.setVisible(false);
        jpresults.setVisible(true);
    }//GEN-LAST:event_jmresultsActionPerformed

    private void jmnewmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnewmarksActionPerformed
        // TODO add your handling code here:
         jpresults.setVisible(false);
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(false);
        jpnewmarks.setVisible(true);
    }//GEN-LAST:event_jmnewmarksActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamDepartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem jmclassanalysis;
    private javax.swing.JMenuItem jmlogout;
    private javax.swing.JMenuItem jmnewmarks;
    private javax.swing.JMenuItem jmresults;
    private javax.swing.JMenuItem jmstudenmarks;
    private javax.swing.JMenuItem jmsubjectanalysis;
    private javax.swing.JPanel jpclassanalysis;
    private javax.swing.JPanel jpnewmarks;
    private javax.swing.JPanel jpresults;
    private javax.swing.JPanel jpstudentmarks;
    private javax.swing.JPanel jpsubjectanalysis;
    // End of variables declaration//GEN-END:variables
}
