/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author owner
 */
public class ExamDepartment extends javax.swing.JFrame {

    /**
     * Creates new form ExamDepartment
     */
    
     Statement st;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    String username = "sql2366456";
    String password = "jI3%cT2!";
    String url = "jdbc:mysql://sql2.freemysqlhosting.net:3306/sql2366456";
    
    
    public ExamDepartment() {
        initComponents();
        
        hidepanels();
        loadexamentrytable();
        loadresultstable();
    }
    
    final public void hidepanels(){
        jpnewmarks.setVisible(false);
        jpresults.setVisible(false);
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(false);
    }
    final public void loadexamentrytable(){
    DefaultTableModel stm = new DefaultTableModel();
    stm.addColumn("FirstName");
    stm.addColumn("NEMIS");
    stm.addColumn("MATHS");
    stm.addColumn("ENGLISH");
    stm.addColumn("KISWAHILi");
    stm.addColumn("SCIENCE");
    stm.addColumn("SOCIAL");
    tblmarksentry.setModel(stm);
    }
    
    final public void loadresultstable(){
        DefaultTableModel stm = new DefaultTableModel();
    stm.addColumn("FirstNane");
    stm.addColumn("MiddleName");
    stm.addColumn("LastName");
    stm.addColumn("Class");
    stm.addColumn("Stream");
    stm.addColumn("NEMIS");
    stm.addColumn("MATHS");
    stm.addColumn("ENGLISH");
    stm.addColumn("KISWAHILi");
    stm.addColumn("SCIENCE");
    stm.addColumn("SOCIAL");
    stm.addColumn("Position");
    stm.addColumn("Avarage");
    stm.addColumn("TotalMarks");
    tblresults.setModel(stm); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jpnewmarks = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtexamyear = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbclass = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbexamterm = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbexamseries = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblmarksentry = new javax.swing.JTable();
        jpresults = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox7 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblresults = new javax.swing.JTable();
        jpstudentmarks = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jpclassanalysis = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel11 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jpanalyticpanel = new javax.swing.JPanel();
        jpsubjectgraph = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jptreadgraph = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jpclasschart = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jpsubjectanalysis = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jLabel38 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jpgeneralsubjectgraph = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jmnewmarks = new javax.swing.JMenuItem();
        jmresults = new javax.swing.JMenuItem();
        jmstudenmarks = new javax.swing.JMenuItem();
        jmlogout = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmclassanalysis = new javax.swing.JMenuItem();
        jmsubjectanalysis = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 600));
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(1150, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(1150, 600));
        jPanel1.setLayout(null);

        jpnewmarks.setBackground(new java.awt.Color(255, 255, 255));
        jpnewmarks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "New Marks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpnewmarks.setMinimumSize(new java.awt.Dimension(1130, 570));
        jpnewmarks.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel1.setText("Add Year  :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(11, 21, 70, 14);

        txtexamyear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtexamyearActionPerformed(evt);
            }
        });
        jPanel2.add(txtexamyear);
        txtexamyear.setBounds(80, 20, 120, 20);

        jLabel2.setText("Class  :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 60, 60, 14);

        cmbclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel2.add(cmbclass);
        cmbclass.setBounds(80, 60, 120, 20);

        jLabel3.setText("Term :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(300, 20, 50, 14);

        cmbexamterm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel2.add(cmbexamterm);
        cmbexamterm.setBounds(370, 20, 130, 20);

        jLabel4.setText("Exam Module  :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(260, 60, 90, 14);

        cmbexamseries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Series 1", "Series 2", "Series 3", "Series 4" }));
        cmbexamseries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbexamseriesActionPerformed(evt);
            }
        });
        jPanel2.add(cmbexamseries);
        cmbexamseries.setBounds(370, 60, 130, 20);

        jButton1.setText("Create new Marks Entry");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(530, 40, 280, 40);

        jButton2.setText("Upload New Marks");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(830, 40, 250, 40);

        jpnewmarks.add(jPanel2);
        jPanel2.setBounds(6, 16, 1100, 100);

        tblmarksentry.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblmarksentry);

        jpnewmarks.add(jScrollPane1);
        jScrollPane1.setBounds(12, 140, 1090, 410);

        jPanel1.add(jpnewmarks);
        jpnewmarks.setBounds(10, 20, 1130, 570);

        jpresults.setBackground(new java.awt.Color(255, 255, 255));
        jpresults.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Results", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpresults.setMinimumSize(new java.awt.Dimension(1130, 570));
        jpresults.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel5.setText("Year :");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 20, 60, 14);

        jLabel6.setText("Class  :");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 60, 60, 14);

        jLabel7.setText("Term :");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(350, 20, 60, 14);

        jLabel8.setText("Series  :");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(350, 60, 70, 14);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        jPanel3.add(jComboBox4);
        jComboBox4.setBounds(100, 20, 170, 20);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel3.add(jComboBox5);
        jComboBox5.setBounds(100, 50, 170, 20);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel3.add(jComboBox6);
        jComboBox6.setBounds(420, 20, 180, 20);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Series 1", "Series 2", "Series 3", "Series 4" }));
        jPanel3.add(jComboBox7);
        jComboBox7.setBounds(420, 50, 180, 20);

        jButton3.setText("Print All ");
        jPanel3.add(jButton3);
        jButton3.setBounds(850, 40, 240, 40);

        jButton4.setText("View Results");
        jPanel3.add(jButton4);
        jButton4.setBounds(630, 40, 200, 40);

        jpresults.add(jPanel3);
        jPanel3.setBounds(10, 20, 1100, 100);

        tblresults.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblresults);

        jpresults.add(jScrollPane2);
        jScrollPane2.setBounds(10, 130, 1100, 402);

        jPanel1.add(jpresults);
        jpresults.setBounds(10, 20, 1130, 570);

        jpstudentmarks.setBackground(new java.awt.Color(255, 255, 255));
        jpstudentmarks.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Student Marks", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpstudentmarks.setMinimumSize(new java.awt.Dimension(1130, 570));
        jpstudentmarks.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);
        jPanel5.add(jTextField5);
        jTextField5.setBounds(120, 10, 110, 20);

        jLabel20.setText("ADMIN/NEMIS  :");
        jPanel5.add(jLabel20);
        jLabel20.setBounds(10, 10, 90, 14);

        jLabel21.setText("Class :");
        jPanel5.add(jLabel21);
        jLabel21.setBounds(242, 10, 50, 14);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel5.add(jComboBox8);
        jComboBox8.setBounds(310, 10, 120, 20);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jPanel5.add(jComboBox9);
        jComboBox9.setBounds(520, 10, 120, 20);

        jLabel22.setText("Term :");
        jPanel5.add(jLabel22);
        jLabel22.setBounds(451, 10, 50, 14);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Series 1", "Series 2", "Series 3", "Series 4" }));
        jPanel5.add(jComboBox10);
        jComboBox10.setBounds(740, 10, 120, 20);

        jLabel23.setText("Module");
        jPanel5.add(jLabel23);
        jLabel23.setBounds(662, 10, 60, 14);

        jButton7.setText("Sreach");
        jPanel5.add(jButton7);
        jButton7.setBounds(900, 10, 170, 23);

        jpstudentmarks.add(jPanel5);
        jPanel5.setBounds(16, 27, 1090, 110);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jLabel16.setText("MName :");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(530, 30, 60, 14);
        jPanel7.add(jTextField1);
        jTextField1.setBounds(600, 30, 150, 20);
        jPanel7.add(jTextField2);
        jTextField2.setBounds(360, 30, 150, 20);

        jLabel17.setText("FName :");
        jPanel7.add(jLabel17);
        jLabel17.setBounds(270, 30, 60, 14);
        jPanel7.add(jTextField3);
        jTextField3.setBounds(130, 30, 110, 20);

        jLabel18.setText("00");
        jPanel7.add(jLabel18);
        jLabel18.setBounds(110, 300, 90, 14);
        jPanel7.add(jTextField4);
        jTextField4.setBounds(860, 30, 170, 20);

        jLabel19.setText("LName");
        jPanel7.add(jLabel19);
        jLabel19.setBounds(770, 30, 60, 14);

        jLabel24.setText("Maths :");
        jPanel7.add(jLabel24);
        jLabel24.setBounds(50, 100, 50, 14);
        jPanel7.add(jTextField6);
        jTextField6.setBounds(120, 100, 60, 20);

        jLabel25.setText("English :");
        jPanel7.add(jLabel25);
        jLabel25.setBounds(40, 140, 60, 14);
        jPanel7.add(jTextField7);
        jTextField7.setBounds(120, 140, 60, 20);

        jLabel26.setText("Kiswahili :");
        jPanel7.add(jLabel26);
        jLabel26.setBounds(40, 180, 60, 14);
        jPanel7.add(jTextField8);
        jTextField8.setBounds(120, 180, 60, 20);

        jLabel27.setText("Science :");
        jPanel7.add(jLabel27);
        jLabel27.setBounds(40, 220, 60, 14);
        jPanel7.add(jTextField9);
        jTextField9.setBounds(120, 220, 60, 20);
        jPanel7.add(jTextField10);
        jTextField10.setBounds(120, 260, 60, 20);

        jLabel28.setText("Social :");
        jPanel7.add(jLabel28);
        jLabel28.setBounds(40, 260, 60, 14);

        jLabel29.setText("Total Score :");
        jPanel7.add(jLabel29);
        jLabel29.setBounds(20, 300, 90, 14);

        jLabel30.setText("ADMIN/NEMIS  :");
        jPanel7.add(jLabel30);
        jLabel30.setBounds(20, 30, 90, 14);

        jLabel31.setText("Class Position  : 1");
        jPanel7.add(jLabel31);
        jLabel31.setBounds(250, 230, 140, 14);

        jLabel32.setText("Class Avarage :    258");
        jPanel7.add(jLabel32);
        jLabel32.setBounds(250, 110, 150, 14);

        jLabel33.setText("Class Entry : 128");
        jPanel7.add(jLabel33);
        jLabel33.setBounds(250, 140, 160, 14);

        jLabel34.setText("Stream Entry : 40");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(250, 170, 150, 14);

        jLabel35.setText("Overal Position : 2");
        jPanel7.add(jLabel35);
        jLabel35.setBounds(250, 200, 160, 14);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8);
        jPanel8.setBounds(570, 90, 460, 280);

        jpstudentmarks.add(jPanel7);
        jPanel7.setBounds(10, 150, 1100, 410);

        jPanel1.add(jpstudentmarks);
        jpstudentmarks.setBounds(10, 20, 1130, 570);

        jpclassanalysis.setBackground(new java.awt.Color(255, 255, 255));
        jpclassanalysis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Class Analysis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpclassanalysis.setMinimumSize(new java.awt.Dimension(1130, 570));
        jpclassanalysis.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel9.setText("Select Class :");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(14, 20, 80, 14);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel4.add(jComboBox1);
        jComboBox1.setBounds(120, 20, 110, 20);

        jLabel10.setText("Year :");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 50, 50, 14);
        jPanel4.add(jYearChooser1);
        jYearChooser1.setBounds(120, 50, 110, 20);

        jLabel11.setText("Term :");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(250, 20, 50, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(310, 20, 100, 20);

        jButton5.setText("View Analysis");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(60, 90, 170, 30);

        jButton6.setText("Print Analysis");
        jPanel4.add(jButton6);
        jButton6.setBounds(250, 90, 170, 30);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 128, Short.MAX_VALUE)
        );

        jPanel4.add(jPanel6);
        jPanel6.setBounds(450, 0, 640, 130);

        jLabel12.setText("Series :");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(250, 50, 50, 14);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Series 1", "Series 2", "Series 3", "Series 4" }));
        jPanel4.add(jComboBox3);
        jComboBox3.setBounds(310, 50, 100, 20);

        jpclassanalysis.add(jPanel4);
        jPanel4.setBounds(16, 28, 1090, 130);

        jpanalyticpanel.setBackground(new java.awt.Color(255, 255, 255));
        jpanalyticpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpanalyticpanel.setLayout(null);

        jpsubjectgraph.setLayout(new java.awt.BorderLayout());

        jLabel15.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel15.setText("SUBJECT AVARAGE");
        jpsubjectgraph.add(jLabel15, java.awt.BorderLayout.CENTER);

        jpanalyticpanel.add(jpsubjectgraph);
        jpsubjectgraph.setBounds(10, 10, 340, 160);

        jptreadgraph.setLayout(new java.awt.BorderLayout());

        jLabel14.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel14.setText("GENERAL  CLASS AVARAGE TREAND");
        jptreadgraph.add(jLabel14, java.awt.BorderLayout.CENTER);

        jpanalyticpanel.add(jptreadgraph);
        jptreadgraph.setBounds(10, 190, 1090, 180);

        jpclasschart.setLayout(new java.awt.BorderLayout());

        jLabel13.setFont(new java.awt.Font("Wide Latin", 0, 18)); // NOI18N
        jLabel13.setText("CLASS   GENERAL  ANALYSIS");
        jpclasschart.add(jLabel13, java.awt.BorderLayout.CENTER);

        jpanalyticpanel.add(jpclasschart);
        jpclasschart.setBounds(360, 10, 730, 160);

        jpclassanalysis.add(jpanalyticpanel);
        jpanalyticpanel.setBounds(10, 170, 1110, 390);

        jPanel1.add(jpclassanalysis);
        jpclassanalysis.setBounds(10, 20, 1130, 570);

        jpsubjectanalysis.setBackground(new java.awt.Color(255, 255, 255));
        jpsubjectanalysis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Subject Analysis", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpsubjectanalysis.setMinimumSize(new java.awt.Dimension(1130, 570));
        jpsubjectanalysis.setPreferredSize(new java.awt.Dimension(1130, 570));
        jpsubjectanalysis.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(null);

        jButton8.setText("View Analysis");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton8);
        jButton8.setBounds(650, 20, 150, 30);

        jLabel36.setText("Class :");
        jPanel9.add(jLabel36);
        jLabel36.setBounds(10, 20, 60, 14);

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox11);
        jComboBox11.setBounds(80, 20, 100, 20);

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox12);
        jComboBox12.setBounds(280, 20, 100, 20);

        jLabel37.setText("Class :");
        jPanel9.add(jLabel37);
        jLabel37.setBounds(210, 20, 60, 14);

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox13);
        jComboBox13.setBounds(500, 20, 100, 20);

        jLabel38.setText("Class :");
        jPanel9.add(jLabel38);
        jLabel38.setBounds(420, 20, 60, 14);

        jButton9.setText("Print ");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton9);
        jButton9.setBounds(920, 20, 110, 30);

        jpsubjectanalysis.add(jPanel9);
        jPanel9.setBounds(20, 30, 1080, 70);

        jpgeneralsubjectgraph.setBackground(new java.awt.Color(255, 255, 255));
        jpgeneralsubjectgraph.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jpgeneralsubjectgraph.setLayout(new java.awt.BorderLayout());
        jpsubjectanalysis.add(jpgeneralsubjectgraph);
        jpgeneralsubjectgraph.setBounds(30, 130, 1060, 160);

        jPanel1.add(jpsubjectanalysis);
        jpsubjectanalysis.setBounds(10, 20, 1130, 570);

        jMenu2.setText("Action");

        jmnewmarks.setText("New Marks");
        jmnewmarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmnewmarksMouseClicked(evt);
            }
        });
        jmnewmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnewmarksActionPerformed(evt);
            }
        });
        jMenu2.add(jmnewmarks);

        jmresults.setText("Results");
        jmresults.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmresultsMouseClicked(evt);
            }
        });
        jmresults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmresultsActionPerformed(evt);
            }
        });
        jMenu2.add(jmresults);

        jmstudenmarks.setText("Sutent Marks");
        jmstudenmarks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmstudenmarksMouseClicked(evt);
            }
        });
        jmstudenmarks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmstudenmarksActionPerformed(evt);
            }
        });
        jMenu2.add(jmstudenmarks);

        jmlogout.setText("Logout");
        jmlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmlogoutMouseClicked(evt);
            }
        });
        jmlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlogoutActionPerformed(evt);
            }
        });
        jMenu2.add(jmlogout);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Analytics");

        jmclassanalysis.setText("Class Analysis");
        jmclassanalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmclassanalysisMouseClicked(evt);
            }
        });
        jmclassanalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmclassanalysisActionPerformed(evt);
            }
        });
        jMenu3.add(jmclassanalysis);

        jmsubjectanalysis.setText("Subject Analysis");
        jmsubjectanalysis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmsubjectanalysisMouseClicked(evt);
            }
        });
        jmsubjectanalysis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmsubjectanalysisActionPerformed(evt);
            }
        });
        jMenu3.add(jmsubjectanalysis);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmnewmarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmnewmarksMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jmnewmarksMouseClicked

    private void jmresultsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmresultsMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jmresultsMouseClicked

    private void jmstudenmarksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmstudenmarksMouseClicked
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jmstudenmarksMouseClicked

    private void jmlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmlogoutMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jmlogoutMouseClicked

    private void jmclassanalysisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmclassanalysisMouseClicked
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_jmclassanalysisMouseClicked

    private void jmsubjectanalysisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmsubjectanalysisMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmsubjectanalysisMouseClicked

    private void jmsubjectanalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmsubjectanalysisActionPerformed
        // TODO add your handling code here:
        jpnewmarks.setVisible(false);
        jpresults.setVisible(false);
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(true);
    }//GEN-LAST:event_jmsubjectanalysisActionPerformed

    private void jmclassanalysisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmclassanalysisActionPerformed
        // TODO add your handling code here:
           jpsubjectanalysis.setVisible(false);
        jpnewmarks.setVisible(false);
        jpresults.setVisible(false);
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(true);
    }//GEN-LAST:event_jmclassanalysisActionPerformed

    private void jmlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginAccounts().setVisible(true);
    }//GEN-LAST:event_jmlogoutActionPerformed

    private void jmstudenmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmstudenmarksActionPerformed
        // TODO add your handling code here:
         jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(false);
        jpnewmarks.setVisible(false);
        jpresults.setVisible(false);
        jpstudentmarks.setVisible(true);
    }//GEN-LAST:event_jmstudenmarksActionPerformed

    private void jmresultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmresultsActionPerformed
        // TODO add your handling code here:
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(false);
        jpnewmarks.setVisible(false);
        jpresults.setVisible(true);
    }//GEN-LAST:event_jmresultsActionPerformed

    private void jmnewmarksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnewmarksActionPerformed
        // TODO add your handling code here:
         jpresults.setVisible(false);
        jpstudentmarks.setVisible(false);
        jpclassanalysis.setVisible(false);
        jpsubjectanalysis.setVisible(false);
        jpnewmarks.setVisible(true);
    }//GEN-LAST:event_jmnewmarksActionPerformed

    private void cmbexamseriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbexamseriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbexamseriesActionPerformed

    private void txtexamyearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtexamyearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtexamyearActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txtexamyear.getText().length() > 4){
            JOptionPane.showMessageDialog(null,"year erro more digits");
        }else if(txtexamyear.getText().length() < 4){
        JOptionPane.showMessageDialog(null,"year erro less digits");
    }else{
            JOptionPane.showMessageDialog(null,"correct");
            
                 DefaultTableModel stm = new DefaultTableModel();
    stm.addColumn("FirstName");
    stm.addColumn("NEMIS");
    stm.addColumn("MATHS");
    stm.addColumn("ENGLISH");
    stm.addColumn("KISWAHILI");
    stm.addColumn("SCIENCE");
    stm.addColumn("SOCIAL");
    tblmarksentry.setModel(stm);
    // try select specific car  data to populated the table
        try{
                con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            String selectecar = "SELECT * FROM tblstudentdetails WHERE CLASS = ? ";
            pst = con.prepareStatement(selectecar);
            pst.setString(1, (String) cmbclass.getSelectedItem());
            rs = pst.executeQuery();
                  
            while(rs.next()){
               String name = rs.getString("FNAME");
               String admin = rs.getString("ADIMN");
               String maths = "";
               String english = "";
               String kiswahili = "";
               String science = "";
               String social = "";
               
               //ARRAY DATA TO DISPLAY
               String tbldata []= {name,admin,maths,english,kiswahili,science,social};
               DefaultTableModel dtmdata = (DefaultTableModel)tblmarksentry.getModel();
               dtmdata.addRow(tbldata);
            }
        }catch(SQLException ex){
        JOptionPane.showMessageDialog(null,"Error" + ex,"PRINCE WHEEL",JOptionPane.WARNING_MESSAGE);
        }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
             /* if(!"".equals(txtexamyear.getText())){
      try{
      
           con = DriverManager.getConnection(url,username,password);
             st = con.createStatement();
             String sqllogmessage = "INSERT INTO tblstudentmarks (YOEXAM,TERM,CLASS,SERIES,FNAME,ADMIN,MATHS,ENGLISH,KISWAHILI,SCIENCE,SOCIAL) VALUES"
                     + " ('"+txtexamyear.getText()+"','"+cmbexamterm.getSelectedItem()+"','"+cmbclass.getSelectedItem()+"',"
                     + "'"+cmbexamseries.getSelectedItem()+"','"+tblmarksentry.getColumnName(0)+"','"+tblmarksentry.getColumnName(1)+"',"
                     + "'"+tblmarksentry.getColumnName(2)+"',"
                     + "'"+tblmarksentry.getColumnName(3)+"','"+tblmarksentry.getColumnName(4)+"','"+tblmarksentry.getColumnName(5)+"',"
                     + "'"+tblmarksentry.getColumnName(6)+"')";
             st.execute(sqllogmessage);
             JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">New Student Registered</i></HTML>","School",JOptionPane.INFORMATION_MESSAGE);
       }catch(SQLIntegrityConstraintViolationException e){
        JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Student Already Exists</i></HTML>","School",JOptionPane.INFORMATION_MESSAGE);  
      }
      catch(HeadlessException | SQLException ex){
   JOptionPane.showMessageDialog(null, "error"+ ex,"School",JOptionPane.INFORMATION_MESSAGE);

       }
      
       }else{
           JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Fill Students details !</i></HTML>","School",JOptionPane.WARNING_MESSAGE);
       }
        */
             
                            



                    try{

                         int rows=tblmarksentry.getRowCount();
                           
                           con = DriverManager.getConnection(url,username,password);
                           st = con.createStatement();
                           con.setAutoCommit(false);

                     String addnewmarks = "Insert into tblstudentmarks (YOEXAM,TERM,CLASS,SERIES,FNAME,ADMIN,MATHS,ENGLISH,KISWAHILI,SCIENCE,SOCIAL) "
                             + "values ('"+txtexamyear.getText()+"','"+cmbexamterm.getSelectedItem()+"','"+cmbclass.getSelectedItem()+"',"
                             + "'"+cmbexamseries.getSelectedItem()+"',?,?,?,?,?,?,?)";
                           pst = con.prepareStatement(addnewmarks);
                         for(int row = 0; row<rows; row++)
                 {
                              String fname = (String)tblmarksentry.getValueAt(row, 0);
                              String nemis = (String)tblmarksentry.getValueAt(row, 1);
                              String maths = (String)tblmarksentry.getValueAt(row, 2);
                              String english = (String)tblmarksentry.getValueAt(row, 3);
                              String kiswahili = (String)tblmarksentry.getValueAt(row, 4);
                              String science = (String)tblmarksentry.getValueAt(row, 5);
                              String social = (String)tblmarksentry.getValueAt(row, 6);
                        pst.setString(1, fname);
                        pst.setString(2, nemis);
                        pst.setString(3, maths);
                        pst.setString(4, english);
                        pst.setString(5, kiswahili);
                        pst.setString(6, science);
                        pst.setString(7, social);

                       pst.addBatch();
                 }
          pst.executeBatch();
          con.commit();
                       JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">New Student Registered</i></HTML>","School",JOptionPane.INFORMATION_MESSAGE);

        }
          catch(SQLException ex){
               JOptionPane.showMessageDialog(null, "error"+ ex,"School",JOptionPane.INFORMATION_MESSAGE);
                   }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
        // Subject graph data
        DefaultCategoryDataset dcd = new DefaultCategoryDataset(); 
         dcd.setValue(60, "Mean", "Maths");
         dcd.setValue(56, "Mean", "English");
         dcd.setValue(62, "Mean", "Kiswahili");
         dcd.setValue(59, "Mean", "Science");
         dcd.setValue(64, "Mean", "Social");
         
         JFreeChart barGraph = ChartFactory.createBarChart("Subject Mean Score", "Subjects", "Mean Mark", dcd, PlotOrientation.VERTICAL, rootPaneCheckingEnabled, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
         
         CategoryPlot myPlot =  barGraph.getCategoryPlot();
         myPlot.setRangeGridlinePaint(Color.BLUE);
         myPlot.setBackgroundPaint(Color.WHITE);
         
         
         ChartPanel myChart = new ChartPanel(barGraph);
         jpsubjectgraph.removeAll();
         jpsubjectgraph.add(myChart, BorderLayout.CENTER);
         jpsubjectgraph.validate();
         
         // Class Treand
         
         DefaultCategoryDataset dcdtread = new DefaultCategoryDataset();
          dcdtread.setValue(55.5, "Avarage Mean", "S1/T1");
          dcdtread.setValue(54.9, "Avarage Mean", "S2/T1");
          dcdtread.setValue(57.3, "Avarage Mean", "S3/T1");
          dcdtread.setValue(65.5, "Avarage Mean", "S1/2");
          dcdtread.setValue(61.7, "Avarage Mean", "S2/T2");
          dcdtread.setValue(60.1, "Avarage Mean", "S3/T2");
          dcdtread.setValue(53.5, "Avarage Mean", "S1/T3");
          dcdtread.setValue(59.8, "Avarage Mean", "S2/T3");
          dcdtread.setValue(62.0, "Avarage Mean", "S3/T3");
          
          JFreeChart mylinegraph = ChartFactory.createLineChart("Treanding Avarage", "Series & Term", "Avarage Mean", dcdtread, PlotOrientation.VERTICAL, rootPaneCheckingEnabled, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
          
          CategoryPlot myline = mylinegraph.getCategoryPlot();
          myline.setRangeGridlinePaint(Color.GREEN);
          myline.setBackgroundPaint(Color.WHITE);
         
          
          ChartPanel linepanel = new ChartPanel(mylinegraph);
          jptreadgraph.removeAll();
          jptreadgraph.add(linepanel, BorderLayout.CENTER);
          jptreadgraph.validate();
          
          // Class analtysis data
          
          DefaultCategoryDataset dcdcalssdata = new  DefaultCategoryDataset();
          dcdcalssdata.setValue(55.5, "Class Avarge","Avarage");
          dcdcalssdata.setValue(78.6, "High mark","Avarage");
          dcdcalssdata.setValue(32.3, "Low Mark","Avarage");
          dcdcalssdata.setValue(78, "Subject HighMark","Maths");
          dcdcalssdata.setValue(22, "Subject LowMark","Maths");
          dcdcalssdata.setValue(85, "Subject HighMark","English");
          dcdcalssdata.setValue(38, "Subject LowMark","English");
          dcdcalssdata.setValue(87, "Subject HighMark","Kiswahili");
          dcdcalssdata.setValue(41, "Subject LowMark","Kiswahili");
          dcdcalssdata.setValue(91, "Subject HighMark","Science");
          dcdcalssdata.setValue(38, "Subject LowMark","Science");
          dcdcalssdata.setValue(90, "Subject HighMark","Social");
          dcdcalssdata.setValue(26, "Subject LowMark","Social");
          
          JFreeChart mylargegraph = ChartFactory.createBarChart("Class General Analysis", "Category Data", "Total marks", dcdcalssdata, PlotOrientation.VERTICAL, rootPaneCheckingEnabled, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
          
          CategoryPlot myclassgraph = mylargegraph.getCategoryPlot();
          myclassgraph.setRangeGridlinePaint(Color.MAGENTA);
          myclassgraph.setBackgroundPaint(Color.WHITE);
          
          ChartPanel classgraph = new ChartPanel(mylargegraph);
          jpclasschart.removeAll();
          jpclasschart.add(classgraph, BorderLayout.CENTER);
          jpclasschart.validate();
         
         
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
         DefaultCategoryDataset dcdcalssdata = new  DefaultCategoryDataset();
   
          dcdcalssdata.setValue(78, "Subject HighMark","Maths");
          dcdcalssdata.setValue(50, "Subject Avarage","Maths");
          dcdcalssdata.setValue(22, "Subject LowMark","Maths");
          dcdcalssdata.setValue(85, "Subject HighMark","English");
          dcdcalssdata.setValue(65, "Subject Avarage","English");
          dcdcalssdata.setValue(38, "Subject LowMark","English");
          dcdcalssdata.setValue(87, "Subject HighMark","Kiswahili");
          dcdcalssdata.setValue(67, "Subject Avarage","Kiswahili");
          dcdcalssdata.setValue(41, "Subject LowMark","Kiswahili");
          dcdcalssdata.setValue(91, "Subject HighMark","Science");
          dcdcalssdata.setValue(70, "Subject Avarage","Science");
          dcdcalssdata.setValue(38, "Subject LowMark","Science");
          dcdcalssdata.setValue(90, "Subject HighMark","Social");
          dcdcalssdata.setValue(63, "Subject Avarage","Social");
          dcdcalssdata.setValue(26, "Subject LowMark","Social");
          
          JFreeChart mylargegraph = ChartFactory.createBarChart("Class Subject Analysis", "Category Data", "Total marks", dcdcalssdata, PlotOrientation.VERTICAL, rootPaneCheckingEnabled, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
          
          CategoryPlot myclassgraph = mylargegraph.getCategoryPlot();
          myclassgraph.setRangeGridlinePaint(Color.MAGENTA);
          myclassgraph.setBackgroundPaint(Color.WHITE);
          
          ChartPanel classgraph = new ChartPanel(mylargegraph);
          jpgeneralsubjectgraph.removeAll();
          jpgeneralsubjectgraph.add(classgraph, BorderLayout.CENTER);
          jpgeneralsubjectgraph.validate();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExamDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExamDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExamDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExamDepartment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExamDepartment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbclass;
    private javax.swing.JComboBox<String> cmbexamseries;
    private javax.swing.JComboBox<String> cmbexamterm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JMenuItem jmclassanalysis;
    private javax.swing.JMenuItem jmlogout;
    private javax.swing.JMenuItem jmnewmarks;
    private javax.swing.JMenuItem jmresults;
    private javax.swing.JMenuItem jmstudenmarks;
    private javax.swing.JMenuItem jmsubjectanalysis;
    private javax.swing.JPanel jpanalyticpanel;
    private javax.swing.JPanel jpclassanalysis;
    private javax.swing.JPanel jpclasschart;
    private javax.swing.JPanel jpgeneralsubjectgraph;
    private javax.swing.JPanel jpnewmarks;
    private javax.swing.JPanel jpresults;
    private javax.swing.JPanel jpstudentmarks;
    private javax.swing.JPanel jpsubjectanalysis;
    private javax.swing.JPanel jpsubjectgraph;
    private javax.swing.JPanel jptreadgraph;
    private javax.swing.JTable tblmarksentry;
    private javax.swing.JTable tblresults;
    private javax.swing.JTextField txtexamyear;
    // End of variables declaration//GEN-END:variables
}
