/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem;

/**
 *
 * @author owner
 */
public final class LoginAccounts extends javax.swing.JFrame {

    /**
     * Creates new form LoginAccounts
     */
    public LoginAccounts() {
        initComponents();
        hidepanel();
    }
    public void hidepanel(){
        jpcreateaccount.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jplogin = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnlogincreate = new javax.swing.JButton();
        jpcreateaccount = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("School Management System");
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(1055, 534));
        jPanel1.setLayout(null);

        jplogin.setBackground(new java.awt.Color(255, 255, 255));
        jplogin.setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account", "Admin", "Exams", "Finance", "Library", "Games" }));
        jplogin.add(jComboBox1);
        jComboBox1.setBounds(80, 40, 220, 20);
        jplogin.add(jTextField1);
        jTextField1.setBounds(80, 100, 220, 20);

        jLabel1.setText("Usrename");
        jplogin.add(jLabel1);
        jLabel1.setBounds(150, 80, 80, 14);

        jLabel2.setText("Password");
        jplogin.add(jLabel2);
        jLabel2.setBounds(160, 130, 60, 14);
        jplogin.add(jPasswordField1);
        jPasswordField1.setBounds(80, 160, 220, 20);

        jCheckBox1.setText("Show Password");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jplogin.add(jCheckBox1);
        jCheckBox1.setBounds(120, 190, 140, 23);

        jButton2.setText("Forgot  Password");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jplogin.add(jButton2);
        jButton2.setBounds(80, 290, 230, 23);

        jButton3.setText("Login");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jplogin.add(jButton3);
        jButton3.setBounds(80, 223, 230, 40);

        jPanel1.add(jplogin);
        jplogin.setBounds(330, 100, 390, 320);

        btnlogincreate.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        btnlogincreate.setForeground(new java.awt.Color(51, 102, 255));
        btnlogincreate.setText("CREATE AN ACCOUNT");
        btnlogincreate.setBorder(null);
        btnlogincreate.setBorderPainted(false);
        btnlogincreate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnlogincreate.setFocusPainted(false);
        btnlogincreate.setOpaque(false);
        btnlogincreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogincreateActionPerformed(evt);
            }
        });
        jPanel1.add(btnlogincreate);
        btnlogincreate.setBounds(670, 471, 370, 40);

        jpcreateaccount.setBackground(new java.awt.Color(255, 255, 255));
        jpcreateaccount.setLayout(null);

        jLabel3.setText("Full Name :");
        jpcreateaccount.add(jLabel3);
        jLabel3.setBounds(10, 20, 80, 14);
        jpcreateaccount.add(jTextField2);
        jTextField2.setBounds(110, 20, 140, 20);
        jpcreateaccount.add(jTextField3);
        jTextField3.setBounds(280, 20, 170, 20);
        jpcreateaccount.add(jTextField4);
        jTextField4.setBounds(470, 20, 160, 20);

        jLabel4.setText("ID   Number  :");
        jpcreateaccount.add(jLabel4);
        jLabel4.setBounds(170, 60, 90, 14);
        jpcreateaccount.add(jTextField5);
        jTextField5.setBounds(280, 90, 170, 20);

        jLabel5.setText("Confirm Password :");
        jpcreateaccount.add(jLabel5);
        jLabel5.setBounds(140, 180, 120, 14);

        jLabel6.setText("Username :");
        jpcreateaccount.add(jLabel6);
        jLabel6.setBounds(180, 100, 80, 14);

        jLabel7.setText("Password :");
        jpcreateaccount.add(jLabel7);
        jLabel7.setBounds(180, 140, 80, 14);

        jButton4.setText("Create Account");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpcreateaccount.add(jButton4);
        jButton4.setBounds(90, 270, 470, 40);
        jpcreateaccount.add(jTextField6);
        jTextField6.setBounds(280, 60, 170, 20);
        jpcreateaccount.add(jPasswordField2);
        jPasswordField2.setBounds(280, 180, 170, 20);
        jpcreateaccount.add(jPasswordField3);
        jPasswordField3.setBounds(280, 140, 170, 20);

        jCheckBox2.setText("Show Password");
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpcreateaccount.add(jCheckBox2);
        jCheckBox2.setBounds(250, 230, 150, 23);

        jPanel1.add(jpcreateaccount);
        jpcreateaccount.setBounds(200, 100, 650, 320);

        jButton1.setText("admin");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(70, 30, 100, 23);

        jButton5.setText("Exams");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(210, 30, 120, 23);

        jButton6.setText("library");
        jPanel1.add(jButton6);
        jButton6.setBounds(360, 30, 140, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1055, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnlogincreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogincreateActionPerformed
        // TODO add your handling code here:
        if(jpcreateaccount.isVisible()){
            btnlogincreate.setText("Create an account");
            jplogin.setVisible(true);
            jpcreateaccount.setVisible(false);
        }else{
            btnlogincreate.setText("Login Instead");
            jpcreateaccount.setVisible(true);
            jplogin.setVisible(false);
        }
    }//GEN-LAST:event_btnlogincreateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       new StudentDetails().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       new ExamDepartment().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAccounts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAccounts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnlogincreate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JPanel jpcreateaccount;
    private javax.swing.JPanel jplogin;
    // End of variables declaration//GEN-END:variables
}
