 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author owner
 */
public class StudentDetails extends javax.swing.JFrame {

    /**
     * Creates new form StudentDetails
     */
    
     Statement st;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    String username = "root";
    String password = "";
    String url = "jdbc:mysql://localhost:3306/schoolmanagement";
   
    
    
    public StudentDetails() {
        initComponents();
        loadstudentsfeetable();
        hidepanels();
        loadsatfftable();
    }
    
    final public void loadstudentsfeetable(){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("NEMIS");
        dtm.addColumn("FirstName");
        dtm.addColumn("MiddleName");
        dtm.addColumn("LastNme");
        dtm.addColumn("Class");
        dtm.addColumn("AmountPaid");
        dtm.addColumn("CurrentBalance");
        dtm.addColumn("TotalAmount");
        
       tblfees.setModel(dtm);
        
    }
    final public void hidepanels(){
        jpaddstudent.setVisible(false);
        jpstaffaccount.setVisible(false);
        jpstaffreport.setVisible(false);
        jpfeestructure.setVisible(false);
        jpfeespayment.setVisible(false);
    }
    final public void loadsatfftable (){
        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID NUMBER");
        dtm.addColumn("Full Name");
        dtm.addColumn("PHONE");
        dtm.addColumn("POSITION");
        dtm.addColumn("CLASS");
        tblstaffaccounts.setModel(dtm);
        tblstaffaccounts.getColumnModel().getColumn(1).setPreferredWidth(200);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpaddstudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtsearchstudent = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbcounty = new javax.swing.JComboBox<>();
        cmbsubcounty = new javax.swing.JComboBox<>();
        cmbward = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtpglname1 = new javax.swing.JTextField();
        txtpgmname1 = new javax.swing.JTextField();
        txtpgfname1 = new javax.swing.JTextField();
        txtpglname2 = new javax.swing.JTextField();
        txtpgmname2 = new javax.swing.JTextField();
        txtpgfname2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtpgcontacts1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtpgcontacts2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbstream = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jcdate = new com.toedter.calendar.JDateChooser();
        cmbgender = new javax.swing.JComboBox<>();
        cmbclass = new javax.swing.JComboBox<>();
        jcyear = new com.toedter.calendar.JYearChooser();
        jpfeespayment = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtsearchsutentfee = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        lbtotalamount = new javax.swing.JLabel();
        lbpaidamount = new javax.swing.JLabel();
        lbcurrentbalance = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        cmbselectedfeeclass = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        bntviewfeestatement = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        lbstudentfullname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblfees = new javax.swing.JTable();
        jpstaffreport = new javax.swing.JPanel();
        jpstaffaccount = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        btnaddstaff = new javax.swing.JButton();
        btnrefresh = new javax.swing.JButton();
        btnupdatestaffreport = new javax.swing.JButton();
        btndeletestaffaccount = new javax.swing.JButton();
        jLabel45 = new javax.swing.JLabel();
        txtstaffid = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        cmbstafflocation = new javax.swing.JComboBox<>();
        jLabel48 = new javax.swing.JLabel();
        cmbstaffgender = new javax.swing.JComboBox<>();
        jLabel49 = new javax.swing.JLabel();
        cmbstaffposition = new javax.swing.JComboBox<>();
        txtstaffphone = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        txtstaffemail = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        cmbstaffaccountcreatable = new javax.swing.JComboBox<>();
        jLabel53 = new javax.swing.JLabel();
        cmballocatedclass = new javax.swing.JComboBox<>();
        jLabel54 = new javax.swing.JLabel();
        cmballocatedactivity = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblstaffaccounts = new javax.swing.JTable();
        jLabel55 = new javax.swing.JLabel();
        cmballocatedstream = new javax.swing.JComboBox<>();
        jpfeestructure = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmstudentmanagement = new javax.swing.JMenuItem();
        jmfee = new javax.swing.JMenuItem();
        jmfeestructure = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmaddaccount = new javax.swing.JMenuItem();
        jmaccountreport = new javax.swing.JMenuItem();
        jmlogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("School Management Systems");
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(970, 446));
        jPanel1.setLayout(null);

        jpaddstudent.setBackground(new java.awt.Color(255, 255, 255));
        jpaddstudent.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Add Student", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpaddstudent.setLayout(null);

        jLabel1.setText("Class :");
        jpaddstudent.add(jLabel1);
        jLabel1.setBounds(50, 380, 50, 14);

        jLabel2.setText("Age :");
        jpaddstudent.add(jLabel2);
        jLabel2.setBounds(40, 120, 50, 14);
        jpaddstudent.add(txtmname);
        txtmname.setBounds(320, 90, 170, 20);

        jLabel3.setText("Full Name :");
        jpaddstudent.add(jLabel3);
        jLabel3.setBounds(20, 90, 80, 14);
        jpaddstudent.add(txtadmin);
        txtadmin.setBounds(120, 340, 170, 20);

        jLabel4.setText("Admin/NEMIS : ");
        jpaddstudent.add(jLabel4);
        jLabel4.setBounds(10, 340, 100, 14);
        jpaddstudent.add(txtlname);
        txtlname.setBounds(510, 90, 170, 20);

        txtfname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnameActionPerformed(evt);
            }
        });
        jpaddstudent.add(txtfname);
        txtfname.setBounds(140, 90, 170, 20);

        jButton1.setText("Add Student");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jpaddstudent.add(jButton1);
        jButton1.setBounds(30, 450, 200, 40);

        jButton2.setText("Update Student");
        jpaddstudent.add(jButton2);
        jButton2.setBounds(400, 450, 200, 40);

        jButton3.setText("Delete Student");
        jpaddstudent.add(jButton3);
        jButton3.setBounds(730, 450, 250, 40);

        jLabel5.setText("Enter Student NEMIS to search  :");
        jpaddstudent.add(jLabel5);
        jLabel5.setBounds(20, 30, 200, 14);
        jpaddstudent.add(txtsearchstudent);
        txtsearchstudent.setBounds(230, 30, 180, 20);

        jButton4.setText("Search");
        jpaddstudent.add(jButton4);
        jButton4.setBounds(450, 20, 150, 30);

        jLabel6.setText("__________________________________________________________________________________________________________________________________________________________________________");
        jpaddstudent.add(jLabel6);
        jLabel6.setBounds(10, 60, 1100, 14);

        jLabel7.setText("Gender :");
        jpaddstudent.add(jLabel7);
        jLabel7.setBounds(390, 130, 60, 14);

        jLabel8.setText("Location/County  :");
        jpaddstudent.add(jLabel8);
        jLabel8.setBounds(10, 170, 100, 14);

        cmbcounty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baringo", "Other" }));
        jpaddstudent.add(cmbcounty);
        cmbcounty.setBounds(140, 170, 160, 20);

        cmbsubcounty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baringo Central", "Baringo South", "Baringo North", "Eldama Ravine", "Mogotio", "Tiaty", "Other" }));
        jpaddstudent.add(cmbsubcounty);
        cmbsubcounty.setBounds(470, 170, 180, 20);

        cmbward.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kapropita", "Koibatek", "Emining", "Mogotio", "Lembus Kwen", "Maji Mazuri/Mumberes", "Ravine", "Kabartonjo", "Kisanana", "Ilchamus", "Mukutani", "Marigat", "Mochongoi", "Bartabwa", "Barwesa", "Kabartonjo", "Saimo/Kipsaraman", "Saimo Soi", "Ewalel/ChapChap", "Lembus Perkera", "Kabarnet", "Tenges", "Lembus", "Churo/Amaya", "Kolowa/Loiwat", "Loyamorok", "Ribkwo", "Tirioko", "Tangulbei/Korossi", "Silale", "Other" }));
        cmbward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbwardActionPerformed(evt);
            }
        });
        jpaddstudent.add(cmbward);
        cmbward.setBounds(820, 170, 170, 20);

        jLabel9.setText("Location/Sub-County  :");
        jpaddstudent.add(jLabel9);
        jLabel9.setBounds(320, 170, 130, 14);

        jLabel10.setText("Location/Ward  :");
        jpaddstudent.add(jLabel10);
        jLabel10.setBounds(700, 170, 110, 14);

        jLabel11.setText("____________________________________________________________________________________________________________________________________________________________________________");
        jpaddstudent.add(jLabel11);
        jLabel11.setBounds(10, 210, 1090, 14);

        jLabel12.setText("Parent/Gaudian Name :  ");
        jpaddstudent.add(jLabel12);
        jLabel12.setBounds(10, 240, 140, 14);
        jpaddstudent.add(txtpglname1);
        txtpglname1.setBounds(530, 240, 170, 20);
        jpaddstudent.add(txtpgmname1);
        txtpgmname1.setBounds(340, 240, 170, 20);
        jpaddstudent.add(txtpgfname1);
        txtpgfname1.setBounds(160, 240, 170, 20);
        jpaddstudent.add(txtpglname2);
        txtpglname2.setBounds(530, 270, 170, 20);
        jpaddstudent.add(txtpgmname2);
        txtpgmname2.setBounds(340, 270, 170, 20);
        jpaddstudent.add(txtpgfname2);
        txtpgfname2.setBounds(160, 270, 170, 20);

        jLabel13.setText("Contacts :");
        jpaddstudent.add(jLabel13);
        jLabel13.setBounds(730, 240, 60, 14);
        jpaddstudent.add(txtpgcontacts1);
        txtpgcontacts1.setBounds(810, 240, 160, 20);

        jLabel14.setText("Contacts :");
        jpaddstudent.add(jLabel14);
        jLabel14.setBounds(730, 270, 60, 14);
        jpaddstudent.add(txtpgcontacts2);
        txtpgcontacts2.setBounds(810, 270, 160, 20);

        jLabel15.setText("______________________________________________________________________________________________________________________________________________________________________________    ");
        jpaddstudent.add(jLabel15);
        jLabel15.setBounds(20, 300, 1080, 14);

        jLabel16.setText("Stream :");
        jpaddstudent.add(jLabel16);
        jLabel16.setBounds(390, 340, 60, 14);

        cmbstream.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "East", "West", "South", "North" }));
        jpaddstudent.add(cmbstream);
        cmbstream.setBounds(480, 340, 200, 20);

        jLabel17.setText("Adminssion   Date :");
        jpaddstudent.add(jLabel17);
        jLabel17.setBounds(340, 380, 110, 14);

        jcdate.setDateFormatString("dd-MM-yyyy");
        jpaddstudent.add(jcdate);
        jcdate.setBounds(480, 380, 200, 20);

        cmbgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jpaddstudent.add(cmbgender);
        cmbgender.setBounds(470, 130, 180, 20);

        cmbclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jpaddstudent.add(cmbclass);
        cmbclass.setBounds(120, 380, 170, 20);
        jpaddstudent.add(jcyear);
        jcyear.setBounds(140, 120, 170, 20);

        jPanel1.add(jpaddstudent);
        jpaddstudent.setBounds(20, 30, 1130, 510);

        jpfeespayment.setBackground(new java.awt.Color(255, 255, 255));
        jpfeespayment.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Fees", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14)))); // NOI18N
        jpfeespayment.setToolTipText("");
        jpfeespayment.setMinimumSize(new java.awt.Dimension(1130, 510));
        jpfeespayment.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jLabel18.setText("Admin/NEMIS :");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 10, 100, 14);
        jPanel2.add(txtsearchsutentfee);
        txtsearchsutentfee.setBounds(130, 10, 130, 20);

        jButton5.setText("Search");
        jPanel2.add(jButton5);
        jButton5.setBounds(290, 10, 120, 30);

        lbtotalamount.setText("Total Amount = 1000");
        jPanel2.add(lbtotalamount);
        lbtotalamount.setBounds(10, 60, 160, 14);

        lbpaidamount.setText("Paid Amount = 0");
        jPanel2.add(lbpaidamount);
        lbpaidamount.setBounds(10, 100, 160, 14);

        lbcurrentbalance.setText("Fee Balance = 1000");
        jPanel2.add(lbcurrentbalance);
        lbcurrentbalance.setBounds(10, 130, 160, 14);

        jLabel22.setText("PAY AMOUNT :");
        jPanel2.add(jLabel22);
        jLabel22.setBounds(220, 100, 90, 14);
        jPanel2.add(jTextField5);
        jTextField5.setBounds(320, 100, 120, 20);

        jButton6.setText("ADD PAY");
        jPanel2.add(jButton6);
        jButton6.setBounds(230, 130, 180, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jLabel23.setText("Select Class");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(19, 25, 90, 14);

        cmbselectedfeeclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel3.add(cmbselectedfeeclass);
        cmbselectedfeeclass.setBounds(130, 20, 130, 20);

        jLabel24.setText("Select Range");
        jPanel3.add(jLabel24);
        jLabel24.setBounds(20, 60, 80, 14);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Students", "Unpaid", "Paid", "Cleared" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox8);
        jComboBox8.setBounds(130, 60, 130, 20);

        bntviewfeestatement.setText("View Statement");
        bntviewfeestatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntviewfeestatementActionPerformed(evt);
            }
        });
        jPanel3.add(bntviewfeestatement);
        bntviewfeestatement.setBounds(60, 110, 160, 30);

        jButton8.setText("Print");
        jPanel3.add(jButton8);
        jButton8.setBounds(403, 123, 140, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(500, 0, 570, 170);

        lbstudentfullname.setText("Student full name");
        jPanel2.add(lbstudentfullname);
        lbstudentfullname.setBounds(220, 60, 240, 14);

        jpfeespayment.add(jPanel2);
        jPanel2.setBounds(31, 35, 1070, 170);

        tblfees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblfees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblfeesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblfees);

        jpfeespayment.add(jScrollPane1);
        jScrollPane1.setBounds(30, 220, 1070, 270);

        jPanel1.add(jpfeespayment);
        jpfeespayment.setBounds(20, 30, 1130, 510);

        jpstaffreport.setBackground(new java.awt.Color(255, 255, 255));
        jpstaffreport.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Staff Account Report", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpstaffreport.setMinimumSize(new java.awt.Dimension(1130, 510));

        javax.swing.GroupLayout jpstaffreportLayout = new javax.swing.GroupLayout(jpstaffreport);
        jpstaffreport.setLayout(jpstaffreportLayout);
        jpstaffreportLayout.setHorizontalGroup(
            jpstaffreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        jpstaffreportLayout.setVerticalGroup(
            jpstaffreportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 488, Short.MAX_VALUE)
        );

        jPanel1.add(jpstaffreport);
        jpstaffreport.setBounds(20, 30, 1130, 510);

        jpstaffaccount.setBackground(new java.awt.Color(255, 255, 255));
        jpstaffaccount.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Staff Accounts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpstaffaccount.setMinimumSize(new java.awt.Dimension(1130, 510));
        jpstaffaccount.setLayout(null);

        jPanel6.setLayout(null);

        jButton13.setText("Delect Staff");
        jPanel6.add(jButton13);
        jButton13.setBounds(20, 300, 190, 50);

        btnaddstaff.setText("Add Staff");
        btnaddstaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddstaffActionPerformed(evt);
            }
        });
        jPanel6.add(btnaddstaff);
        btnaddstaff.setBounds(19, 25, 190, 50);

        btnrefresh.setText("Refresh");
        btnrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrefreshActionPerformed(evt);
            }
        });
        jPanel6.add(btnrefresh);
        btnrefresh.setBounds(20, 90, 190, 50);

        btnupdatestaffreport.setText("Update");
        btnupdatestaffreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdatestaffreportActionPerformed(evt);
            }
        });
        jPanel6.add(btnupdatestaffreport);
        btnupdatestaffreport.setBounds(20, 160, 190, 50);

        btndeletestaffaccount.setText("Delect Account");
        btndeletestaffaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeletestaffaccountActionPerformed(evt);
            }
        });
        jPanel6.add(btndeletestaffaccount);
        btndeletestaffaccount.setBounds(20, 230, 190, 50);

        jpstaffaccount.add(jPanel6);
        jPanel6.setBounds(884, 56, 240, 450);

        jLabel45.setText("Staff ID :");
        jpstaffaccount.add(jLabel45);
        jLabel45.setBounds(30, 40, 70, 14);
        jpstaffaccount.add(txtstaffid);
        txtstaffid.setBounds(120, 40, 140, 20);

        jLabel47.setText("Location :");
        jpstaffaccount.add(jLabel47);
        jLabel47.setBounds(30, 170, 70, 14);

        cmbstafflocation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jpstaffaccount.add(cmbstafflocation);
        cmbstafflocation.setBounds(120, 170, 140, 20);

        jLabel48.setText("Gender :");
        jpstaffaccount.add(jLabel48);
        jLabel48.setBounds(30, 220, 70, 14);

        cmbstaffgender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MALE", "FEMALE" }));
        jpstaffaccount.add(cmbstaffgender);
        cmbstaffgender.setBounds(120, 220, 140, 20);

        jLabel49.setText("Possition :");
        jpstaffaccount.add(jLabel49);
        jLabel49.setBounds(30, 270, 60, 14);

        cmbstaffposition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HEAD OF STAFF", "DEPUTY HEAD", "DOS", "EXAMINNER", "BOARDING MASTER", "CLASS TEACHER", "TEACHER" }));
        jpstaffaccount.add(cmbstaffposition);
        cmbstaffposition.setBounds(120, 270, 140, 20);
        jpstaffaccount.add(txtstaffphone);
        txtstaffphone.setBounds(120, 90, 140, 20);

        jLabel50.setText("Phone NO :");
        jpstaffaccount.add(jLabel50);
        jLabel50.setBounds(30, 90, 70, 14);
        jpstaffaccount.add(txtstaffemail);
        txtstaffemail.setBounds(60, 130, 200, 20);

        jLabel51.setText("Email  :");
        jpstaffaccount.add(jLabel51);
        jLabel51.setBounds(10, 130, 40, 14);

        jLabel52.setText("Account Createtable  :");
        jpstaffaccount.add(jLabel52);
        jLabel52.setBounds(20, 460, 140, 14);

        cmbstaffaccountcreatable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EXAMINATION", "CLASS TEACHER", "DOS", "ADMIN", "LIBRAY", "NONE" }));
        jpstaffaccount.add(cmbstaffaccountcreatable);
        cmbstaffaccountcreatable.setBounds(170, 460, 140, 20);

        jLabel53.setText("Allocated Class :");
        jpstaffaccount.add(jLabel53);
        jLabel53.setBounds(10, 320, 120, 14);

        cmballocatedclass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "0" }));
        cmballocatedclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmballocatedclassActionPerformed(evt);
            }
        });
        jpstaffaccount.add(cmballocatedclass);
        cmballocatedclass.setBounds(150, 320, 110, 20);

        jLabel54.setText("Activity :");
        jpstaffaccount.add(jLabel54);
        jLabel54.setBounds(30, 400, 70, 14);

        cmballocatedactivity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GAMES", "LEARNING ACCESS", "STUDENT AFARES", "NONE" }));
        cmballocatedactivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmballocatedactivityActionPerformed(evt);
            }
        });
        jpstaffaccount.add(cmballocatedactivity);
        cmballocatedactivity.setBounds(120, 400, 140, 20);

        tblstaffaccounts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblstaffaccounts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstaffaccountsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblstaffaccounts);

        jpstaffaccount.add(jScrollPane2);
        jScrollPane2.setBounds(290, 40, 580, 340);

        jLabel55.setText("Stream :");
        jpstaffaccount.add(jLabel55);
        jLabel55.setBounds(30, 360, 70, 14);

        cmballocatedstream.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EAST", "WEST", "SOUTH", "NORTH", "NONE" }));
        cmballocatedstream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmballocatedstreamActionPerformed(evt);
            }
        });
        jpstaffaccount.add(cmballocatedstream);
        cmballocatedstream.setBounds(120, 360, 140, 20);

        jPanel1.add(jpstaffaccount);
        jpstaffaccount.setBounds(20, 30, 1130, 510);

        jpfeestructure.setBackground(new java.awt.Color(255, 255, 255));
        jpfeestructure.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Fee Structure", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 0, 14))); // NOI18N
        jpfeestructure.setMinimumSize(new java.awt.Dimension(1130, 510));
        jpfeestructure.setPreferredSize(new java.awt.Dimension(1130, 510));
        jpfeestructure.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel39.setText("Caution   KSH.0.00");
        jPanel4.add(jLabel39);
        jLabel39.setBounds(200, 330, 140, 14);

        jLabel35.setText("Boarding  KSH.0.00");
        jPanel4.add(jLabel35);
        jLabel35.setBounds(200, 160, 140, 14);

        jLabel37.setText("Activity   KSH.0.00");
        jPanel4.add(jLabel37);
        jLabel37.setBounds(200, 250, 130, 14);

        jLabel38.setText("Maintainance   KSH.0.00");
        jPanel4.add(jLabel38);
        jLabel38.setBounds(200, 290, 140, 14);

        jLabel36.setText("Exams   KSH.0.00");
        jPanel4.add(jLabel36);
        jLabel36.setBounds(200, 200, 130, 14);

        jLabel41.setText("Total  Amount    KSH.0.00");
        jPanel4.add(jLabel41);
        jLabel41.setBounds(170, 410, 190, 14);

        jLabel40.setText("Medical    KSH.0.00");
        jPanel4.add(jLabel40);
        jLabel40.setBounds(200, 370, 150, 14);

        jLabel42.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel42.setText("Class   4");
        jPanel4.add(jLabel42);
        jLabel42.setBounds(130, 90, 300, 30);

        jLabel43.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel43.setText("School Name Post office");
        jPanel4.add(jLabel43);
        jLabel43.setBounds(130, 30, 300, 30);

        jLabel44.setFont(new java.awt.Font("Wide Latin", 0, 12)); // NOI18N
        jLabel44.setText("Year    2020");
        jPanel4.add(jLabel44);
        jLabel44.setBounds(130, 60, 300, 30);

        jpfeestructure.add(jPanel4);
        jPanel4.setBounds(530, 60, 590, 440);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jpfeestructure.add(jComboBox1);
        jComboBox1.setBounds(690, 10, 140, 30);

        jButton9.setText("Print");
        jpfeestructure.add(jButton9);
        jButton9.setBounds(910, 20, 180, 30);

        jLabel25.setText("Select Class :");
        jpfeestructure.add(jLabel25);
        jLabel25.setBounds(570, 20, 100, 14);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jLabel26.setText("Select Year :");
        jPanel5.add(jLabel26);
        jLabel26.setBounds(20, 30, 80, 14);
        jPanel5.add(jYearChooser1);
        jYearChooser1.setBounds(110, 30, 90, 20);

        jLabel27.setText("Boarding :");
        jPanel5.add(jLabel27);
        jLabel27.setBounds(20, 126, 67, 14);
        jPanel5.add(jTextField1);
        jTextField1.setBounds(130, 120, 115, 20);

        jLabel28.setText("Exams :");
        jPanel5.add(jLabel28);
        jLabel28.setBounds(20, 158, 67, 14);
        jPanel5.add(jTextField3);
        jTextField3.setBounds(130, 160, 115, 20);

        jLabel29.setText("Activity :");
        jPanel5.add(jLabel29);
        jLabel29.setBounds(20, 203, 67, 14);
        jPanel5.add(jTextField4);
        jTextField4.setBounds(130, 200, 115, 20);

        jLabel30.setText("Total  Amount   Ksh. 0.00");
        jPanel5.add(jLabel30);
        jLabel30.setBounds(40, 380, 190, 14);

        jLabel31.setText("Class : ");
        jPanel5.add(jLabel31);
        jLabel31.setBounds(210, 30, 50, 14);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jPanel5.add(jComboBox2);
        jComboBox2.setBounds(280, 30, 80, 20);
        jPanel5.add(jTextField6);
        jTextField6.setBounds(130, 320, 115, 20);

        jLabel32.setText("Medical  :");
        jPanel5.add(jLabel32);
        jLabel32.setBounds(20, 320, 67, 14);

        jLabel33.setText("Caution :");
        jPanel5.add(jLabel33);
        jLabel33.setBounds(20, 280, 67, 14);
        jPanel5.add(jTextField7);
        jTextField7.setBounds(130, 280, 115, 20);

        jLabel34.setText("Maintainance :");
        jPanel5.add(jLabel34);
        jLabel34.setBounds(20, 240, 100, 14);
        jPanel5.add(jTextField8);
        jTextField8.setBounds(130, 240, 115, 20);

        jButton10.setText("Update");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton10);
        jButton10.setBounds(290, 430, 160, 40);

        jButton11.setText("Approve");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11);
        jButton11.setBounds(40, 430, 160, 40);

        jButton12.setText("Create");
        jPanel5.add(jButton12);
        jButton12.setBounds(380, 23, 110, 30);

        jpfeestructure.add(jPanel5);
        jPanel5.setBounds(10, 20, 510, 480);

        jPanel1.add(jpfeestructure);
        jpfeestructure.setBounds(20, 30, 1130, 510);

        jMenu1.setText("Students");

        jmstudentmanagement.setText("Student Management");
        jmstudentmanagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmstudentmanagementActionPerformed(evt);
            }
        });
        jMenu1.add(jmstudentmanagement);

        jmfee.setText("Fees");
        jmfee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmfeeActionPerformed(evt);
            }
        });
        jMenu1.add(jmfee);

        jmfeestructure.setText("Fees Structure");
        jmfeestructure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmfeestructureActionPerformed(evt);
            }
        });
        jMenu1.add(jmfeestructure);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Accounts");

        jmaddaccount.setText("Add Account");
        jmaddaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaddaccountActionPerformed(evt);
            }
        });
        jMenu2.add(jmaddaccount);

        jmaccountreport.setText("Accounts Report");
        jmaccountreport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmaccountreportActionPerformed(evt);
            }
        });
        jMenu2.add(jmaccountreport);

        jmlogout.setText("Logout");
        jmlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlogoutActionPerformed(evt);
            }
        });
        jMenu2.add(jmlogout);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       if(!"".equals(txtadmin.getText())&&!"".equals(txtfname.getText()) && !"".equals(txtmname.getText()) 
               && !"".equals(txtpgfname1.getText()) && !"".equals(txtpgmname1.getText()) && !"".equals(txtpgcontacts1.getText()) 
               && !"".equals(jcdate.getDate().toString())){
      try{
      // get other variable 
      java.util.Date admindate;
            java.sql.Date dateofadmin;
            admindate =  jcdate.getDate();
            dateofadmin = new java.sql.Date(admindate.getTime());
           
      
         int yob = jcyear.getYear();
          int studyclass =  Integer.parseInt(cmbclass.getSelectedItem().toString());
          int initialfee = 0;
          
           con = DriverManager.getConnection(url,username,password);
             st = con.createStatement();
             // inserting student personal details 
             String sqlpersonalstdentdetails = "INSERT INTO tblstudentdetails (REGISTRATIONNUMBER,FIRSTNAME,MIDDLENAME,LASTNAME,GENDER,YOB,CLASS,"
                     + "STREAM,ADMISSIONDATE,COUNTY,SUBCOUNTY,WARD) VALUES"
                     + " ('"+txtadmin.getText()+"','"+txtfname.getText()+"','"+txtmname.getText()+"','"+txtlname.getText()+"',"
                     + "'"+cmbgender.getSelectedItem()+"','"+yob+"','"+studyclass+"','"+cmbstream.getSelectedItem()+"','"+dateofadmin+"',"
                     + "'"+cmbcounty.getSelectedItem()+"','"+cmbsubcounty.getSelectedItem()+"','"+cmbward.getSelectedItem()+"')";
             st.execute(sqlpersonalstdentdetails);
             
             // inserting student parent details
                    String sqlstudentparentdetails = "INSERT INTO tblparents (REGISTRATIONNUMBER,PARENTFIRSTNAME,PARENTMIDDLENAME,"
                            + "PARENTLASTNAME,PARENTCONTACTS,PARENTFIRSTNAME2,PARENTMIDDLENAME2,PARENTLASTNAME2,PARENTCONTACTS2) VALUES"
                     + " ('"+txtadmin.getText()+"','"+txtpgfname1.getText()+"','"+txtpgmname1.getText()+"',"
                     + "'"+txtpglname1.getText()+"','"+txtpgcontacts1.getText()+"','"+txtpgfname2.getText()+"','"+txtpgmname2.getText()+"',"
                     + "'"+txtpglname2.getText()+"','"+txtpgcontacts2.getText()+"')";
             st.execute(sqlstudentparentdetails);
             // inserting student feepayment
             
              String sqlstudentfeepayment = "INSERT INTO tblfeepayment (REGISTRATIONNUMBER,CLASS,FIRSTNAME,MIDDLENAME,LASTNAME,TOTAL,"
                      + "PAID,BALANCE) VALUES"
                     + " ('"+txtadmin.getText()+"','"+studyclass+"','"+txtfname.getText()+"','"+txtmname.getText()+"','"+txtlname.getText()+"',"
                      + "'"+initialfee+"','"+initialfee+"','"+initialfee+"')";
             st.execute(sqlstudentfeepayment);
             
             
             JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">New Student Registered</i></HTML>","School",JOptionPane.INFORMATION_MESSAGE);
       }catch(SQLIntegrityConstraintViolationException e){
        JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Student Already Exists</i></HTML>","School",JOptionPane.WARNING_MESSAGE);  
      }
      catch(HeadlessException | SQLException ex){
   JOptionPane.showMessageDialog(null, "error"+ ex,"School",JOptionPane.INFORMATION_MESSAGE);

       }
      catch(NullPointerException npx){
        JOptionPane.showMessageDialog(null,"Please select Date !","School",JOptionPane.INFORMATION_MESSAGE);
        }
      
       }else{
           JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Fill Students details !</i></HTML>","School",JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbwardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbwardActionPerformed

    private void jmlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginAccounts().setVisible(true);
    }//GEN-LAST:event_jmlogoutActionPerformed

    private void jmfeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmfeeActionPerformed
        // TODO add your handling code here:
        
        jpaddstudent.setVisible(false);
        jpstaffaccount.setVisible(false);
        jpstaffreport.setVisible(false);
        jpfeestructure.setVisible(false);
        jpfeespayment.setVisible(true);
    }//GEN-LAST:event_jmfeeActionPerformed

    private void jmstudentmanagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmstudentmanagementActionPerformed
        // TODO add your handling code here:
     
        jpstaffaccount.setVisible(false);
        jpstaffreport.setVisible(false);
        jpfeestructure.setVisible(false);
        jpfeespayment.setVisible(false);
        jpaddstudent.setVisible(true);
    }//GEN-LAST:event_jmstudentmanagementActionPerformed

    private void jmfeestructureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmfeestructureActionPerformed
        // TODO add your handling code here:
          jpstaffaccount.setVisible(false);
        jpstaffreport.setVisible(false);
        
        jpfeespayment.setVisible(false);
        jpaddstudent.setVisible(false);
        jpfeestructure.setVisible(true);
    }//GEN-LAST:event_jmfeestructureActionPerformed

    private void jmaddaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaddaccountActionPerformed
        // TODO add your handling code here:
      
        jpstaffreport.setVisible(false);
        jpfeespayment.setVisible(false);
        jpaddstudent.setVisible(false);
        jpfeestructure.setVisible(false);
          jpstaffaccount.setVisible(true);
    }//GEN-LAST:event_jmaddaccountActionPerformed

    private void jmaccountreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmaccountreportActionPerformed
        // TODO add your handling code here:
        
        jpfeespayment.setVisible(false);
        jpaddstudent.setVisible(false);
        jpfeestructure.setVisible(false);
          jpstaffaccount.setVisible(false);
          jpstaffreport.setVisible(true);
    }//GEN-LAST:event_jmaccountreportActionPerformed

    private void txtfnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnameActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void cmballocatedactivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmballocatedactivityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmballocatedactivityActionPerformed

    private void cmballocatedstreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmballocatedstreamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmballocatedstreamActionPerformed

    private void cmballocatedclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmballocatedclassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmballocatedclassActionPerformed

    private void bntviewfeestatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntviewfeestatementActionPerformed
        // TODO add your handling code here:

        DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("NEMIS");
        dtm.addColumn("FirstName");
        dtm.addColumn("MiddleName");
        dtm.addColumn("LastNme");
        dtm.addColumn("Class");
        dtm.addColumn("AmountPaid");
        dtm.addColumn("CurrentBalance");
        dtm.addColumn("TotalAmount");

        tblfees.setModel(dtm);

        try{

            con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            String selectefee = "SELECT * FROM tblfeepayment WHERE CLASS = ? ";
            pst = con.prepareStatement(selectefee);
            pst.setString(1, (String) cmbselectedfeeclass.getSelectedItem());
            rs = pst.executeQuery();

            while(rs.next()){

                String admin = rs.getString("REGISTRATIONNUMBER");
                String  studentclass =  rs.getString("CLASS");
                String  name =  rs.getString("FIRSTNAME");
                String name2 =  rs.getString("MIDDLENAME");
                String name3 =  rs.getString("LASTNAME");
                String total =  rs.getString("TOTAL");
                String paid =  rs.getString("PAID");
                String balance =  rs.getString("BALANCE");

                //ARRAY DATA TO DISPLAY
                String tbldata []= {admin,name,name2,name3,studentclass,total,paid,balance};
                DefaultTableModel dtmdata = (DefaultTableModel)tblfees.getModel();
                dtmdata.addRow(tbldata);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error" + ex,"School",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bntviewfeestatementActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void tblfeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblfeesMouseClicked
        // TODO add your handling code here:
        
        
        DefaultTableModel dtm = (DefaultTableModel)tblfees.getModel();
        int selectedrowindex = tblfees.getSelectedRow();
        String name = dtm.getValueAt(selectedrowindex, 1).toString();
        String name2 = dtm.getValueAt(selectedrowindex, 2).toString();
        String name3 = dtm.getValueAt(selectedrowindex, 3).toString();
        lbstudentfullname.setText(name + " " + name2 + " " + name3);
        lbtotalamount.setText(" Total Amount : " + dtm.getValueAt(selectedrowindex, 7).toString());
        lbpaidamount.setText(" Amount Paid : " + dtm.getValueAt(selectedrowindex, 5).toString());
        txtsearchsutentfee.setText(dtm.getValueAt(selectedrowindex, 0).toString());
        lbcurrentbalance.setText(" Current balance : " + dtm.getValueAt(selectedrowindex, 6).toString());
    }//GEN-LAST:event_tblfeesMouseClicked

    private void btnaddstaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddstaffActionPerformed
        // TODO add your handling code here:
        
        // add new staff 
        // get staff detail 
        String staffid,phone,email,location,gender,position,allocatedclass,allocatedstream,allocatedactivity,accountcreatable,name;
        staffid = txtstaffid.getText().trim();
        phone = txtstaffphone.getText();
        email = txtstaffemail.getText();
        location = cmbstafflocation.getSelectedItem().toString();
        gender = cmbstaffgender.getSelectedItem().toString();
        position = cmbstaffposition.getSelectedItem().toString();
        allocatedclass = cmballocatedclass.getSelectedItem().toString();
        allocatedstream = cmballocatedstream.getSelectedItem().toString();
        allocatedactivity = cmballocatedactivity.getSelectedItem().toString();
        accountcreatable = cmbstaffaccountcreatable.getSelectedItem().toString();
        name = "";
        
        // insert staff data
        if(!"".equals(staffid)  && !"".equals(phone)){
        try{
            con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            
            String insertstaff = "INSERT into tblteacherdetails (STAFFID,FIRSTNAME,MIDDLENAME,LASTNAME,GENDER,LOCATION,PHONE,EMAIL,"
                    + "POSITION,ALLOCATEDCLASS,STREAM,ACTIVITY,ACCOUNTCREATABLE) VALUES ('"+staffid+"','"+name+"','"+name+"','"+name+"',"
                    + "'"+gender+"','"+location+"','"+phone+"',"
                    + "'"+email+"','"+position+"','"+allocatedclass+"','"+allocatedstream+"','"+allocatedactivity+"','"+accountcreatable+"')";
            st.execute(insertstaff);
            JOptionPane.showMessageDialog(null, "New Staff Addr","School",JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLIntegrityConstraintViolationException e){
        JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Staff Already Exists</i></HTML>","School",JOptionPane.WARNING_MESSAGE);  
      }catch(HeadlessException | SQLException ex){
   JOptionPane.showMessageDialog(null, "error"+ ex,"School",JOptionPane.INFORMATION_MESSAGE);

       }
        }else{
            JOptionPane.showMessageDialog(null, "Fill all Staff Details","School",JOptionPane.INFORMATION_MESSAGE);
            
        }
        
    }//GEN-LAST:event_btnaddstaffActionPerformed

    private void btnrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrefreshActionPerformed
        // TODO add your handling code here:
        
        // selecte staff data
        
         DefaultTableModel dtm = new DefaultTableModel();
        dtm.addColumn("ID NUMBER");
        dtm.addColumn("Full Name");
        dtm.addColumn("PHONE");
        dtm.addColumn("POSITION");
        dtm.addColumn("CLASS");
        tblstaffaccounts.setModel(dtm);
        tblstaffaccounts.getColumnModel().getColumn(1).setPreferredWidth(200);
        tblstaffaccounts.getColumnModel().getColumn(3).setPreferredWidth(100);


        try{

            con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            String selecteacher = "SELECT * FROM tblteacherdetails  ";
            pst = con.prepareStatement(selecteacher);
            rs = pst.executeQuery();

            while(rs.next()){

                String id= rs.getString("STAFFID");
                String  allocatedclass =  rs.getString("ALLOCATEDCLASS");
                String  phone =  rs.getString("PHONE");
                String  name =  rs.getString("FIRSTNAME");
                String name2 =  rs.getString("MIDDLENAME");
                String name3 =  rs.getString("LASTNAME");
                String position =  rs.getString("POSITION");
                

                //ARRAY DATA TO DISPLAY
                String tbldata []= {id,name+ " " + name2 + " " + name3,phone,position,allocatedclass};
                DefaultTableModel dtmdata = (DefaultTableModel)tblstaffaccounts.getModel();
                dtmdata.addRow(tbldata);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error" + ex,"School",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnrefreshActionPerformed

    private void tblstaffaccountsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstaffaccountsMouseClicked
        // TODO add your handling code here:
        
        DefaultTableModel dtm = (DefaultTableModel)tblstaffaccounts.getModel();
        int selectedrow = tblstaffaccounts.getSelectedRow();
         String searchid = (dtm.getValueAt(selectedrow, 0).toString());
         
         try{

            con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            String selecteacher = "SELECT * FROM tblteacherdetails WHERE STAFFID = ?";
            pst = con.prepareStatement(selecteacher);
            pst.setString(1, (String) searchid);
            rs = pst.executeQuery();

            if(rs.next()){

                String id= rs.getString("STAFFID");
                String  allocatedclass =  rs.getString("ALLOCATEDCLASS");
                String  phone =  rs.getString("PHONE");
                String  name =  rs.getString("FIRSTNAME");
                String name2 =  rs.getString("MIDDLENAME");
                String name3 =  rs.getString("LASTNAME");
                String gender = rs.getString("GENDER");
                String position =  rs.getString("POSITION");
                String email =  rs.getString("EMAIL");
                String allocatedstream =  rs.getString("STREAM");
                String activity =  rs.getString("ACTIVITY");
                String accountcreatable =  rs.getString("ACCOUNTCREATABLE");
                String location = rs.getString("LOCATION");

                // DATA TO DISPLAY for update
                
         txtstaffid.setText(id);
        txtstaffphone.setText(phone);
        txtstaffemail.setText(email);
        cmbstafflocation.setSelectedItem(location);
        cmbstaffgender.setSelectedItem(gender);
        cmbstaffposition.setSelectedItem(position);
        cmballocatedclass.setSelectedItem(allocatedclass);
        cmballocatedstream.setSelectedItem(allocatedstream);
        cmballocatedactivity.setSelectedItem(activity);
        cmbstaffaccountcreatable.setSelectedItem(accountcreatable);
                
                
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Error" + ex,"School",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_tblstaffaccountsMouseClicked

    private void btnupdatestaffreportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdatestaffreportActionPerformed
        // TODO add your handling code here:
        
        // update specific staff data 
        if(!"".equals(txtstaffid.getText())){
            try{
                con = DriverManager.getConnection(url,username,password);
                st = con.createStatement();
                
                String updatestaffinfor = "UPDATE tblteacherdetails set PHONE = '"+txtstaffphone.getText()+"',EMAIL ='"+txtstaffemail.getText()+"',"
                        + "POSITION = '"+cmbstaffposition.getSelectedItem()+"',ALLOCATEDCLASS = '"+cmballocatedclass.getSelectedItem()+"',"
                        + "STREAM = '"+cmbstream.getSelectedItem()+"',ACTIVITY = '"+cmballocatedactivity.getSelectedItem()+"',"
                        + "ACCOUNTCREATABLE = '"+cmbstaffaccountcreatable.getSelectedItem()+"'  WHERE  STAFFID = ?";
                pst = con.prepareStatement(updatestaffinfor);
                pst.setString(1 , (String) txtstaffid.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">Staff Details Updated</i></HTML>","School",JOptionPane.INFORMATION_MESSAGE);  
            }catch(SQLException ex){
             JOptionPane.showMessageDialog(null,"Error" + ex,"School",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Fill Staff ID</i></HTML>","School",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnupdatestaffreportActionPerformed

    private void btndeletestaffaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeletestaffaccountActionPerformed
        // TODO add your handling code here:
        
        // delete specific staff login creadentials 
        
        if(!"".equals(txtstaffid.getText())){
            try{
            con = DriverManager.getConnection(url,username,password);
            st = con.createStatement();
            String deletestaffaccount = "DELETE from tblteacheraccount WHERE  STAFFID = ?";
            pst = con.prepareStatement(deletestaffaccount);
            pst.setString(1, (String) txtstaffid.getText());
            pst.execute();
             JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Staff Deleted</i></HTML>","School",JOptionPane.WARNING_MESSAGE);
            }catch(SQLException ex){
                 JOptionPane.showMessageDialog(null,"Error" + ex,"School",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: red; font-size: 12px;\">Fill Staff ID</i></HTML>","School",JOptionPane.WARNING_MESSAGE);
            
        }
    }//GEN-LAST:event_btndeletestaffaccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntviewfeestatement;
    private javax.swing.JButton btnaddstaff;
    private javax.swing.JButton btndeletestaffaccount;
    private javax.swing.JButton btnrefresh;
    private javax.swing.JButton btnupdatestaffreport;
    private javax.swing.JComboBox<String> cmballocatedactivity;
    private javax.swing.JComboBox<String> cmballocatedclass;
    private javax.swing.JComboBox<String> cmballocatedstream;
    private javax.swing.JComboBox<String> cmbclass;
    private javax.swing.JComboBox<String> cmbcounty;
    private javax.swing.JComboBox<String> cmbgender;
    private javax.swing.JComboBox<String> cmbselectedfeeclass;
    private javax.swing.JComboBox<String> cmbstaffaccountcreatable;
    private javax.swing.JComboBox<String> cmbstaffgender;
    private javax.swing.JComboBox<String> cmbstafflocation;
    private javax.swing.JComboBox<String> cmbstaffposition;
    private javax.swing.JComboBox<String> cmbstream;
    private javax.swing.JComboBox<String> cmbsubcounty;
    private javax.swing.JComboBox<String> cmbward;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JDateChooser jcdate;
    private com.toedter.calendar.JYearChooser jcyear;
    private javax.swing.JMenuItem jmaccountreport;
    private javax.swing.JMenuItem jmaddaccount;
    private javax.swing.JMenuItem jmfee;
    private javax.swing.JMenuItem jmfeestructure;
    private javax.swing.JMenuItem jmlogout;
    private javax.swing.JMenuItem jmstudentmanagement;
    private javax.swing.JPanel jpaddstudent;
    private javax.swing.JPanel jpfeespayment;
    private javax.swing.JPanel jpfeestructure;
    private javax.swing.JPanel jpstaffaccount;
    private javax.swing.JPanel jpstaffreport;
    private javax.swing.JLabel lbcurrentbalance;
    private javax.swing.JLabel lbpaidamount;
    private javax.swing.JLabel lbstudentfullname;
    private javax.swing.JLabel lbtotalamount;
    private javax.swing.JTable tblfees;
    private javax.swing.JTable tblstaffaccounts;
    private javax.swing.JTextField txtadmin;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmname;
    private javax.swing.JTextField txtpgcontacts1;
    private javax.swing.JTextField txtpgcontacts2;
    private javax.swing.JTextField txtpgfname1;
    private javax.swing.JTextField txtpgfname2;
    private javax.swing.JTextField txtpglname1;
    private javax.swing.JTextField txtpglname2;
    private javax.swing.JTextField txtpgmname1;
    private javax.swing.JTextField txtpgmname2;
    private javax.swing.JTextField txtsearchstudent;
    private javax.swing.JTextField txtsearchsutentfee;
    private javax.swing.JTextField txtstaffemail;
    private javax.swing.JTextField txtstaffid;
    private javax.swing.JTextField txtstaffphone;
    // End of variables declaration//GEN-END:variables
}
