/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package schoolmanagementsystem;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author owner
 */
public class StudentDetails extends javax.swing.JFrame {

    /**
     * Creates new form StudentDetails
     */
    
     Statement st;
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
    String username = "sql2366456";
    String password = "jI3%cT2!";
    String url = "jdbc:mysql://sql2.freemysqlhosting.net:3306/sql2366456";
   
    
    
    public StudentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtclass = new javax.swing.JTextField();
        txtage = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtmname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtadmin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtlname = new javax.swing.JTextField();
        txtfname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("School Management Systems");
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(970, 446));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel1.setText("Class  :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 90, 80, 14);
        jPanel2.add(txtclass);
        txtclass.setBounds(140, 90, 170, 20);
        jPanel2.add(txtage);
        txtage.setBounds(140, 60, 170, 20);

        jLabel2.setText("Age :");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 60, 80, 14);
        jPanel2.add(txtmname);
        txtmname.setBounds(320, 30, 170, 20);

        jLabel3.setText("Full Name :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(21, 32, 80, 14);
        jPanel2.add(txtadmin);
        txtadmin.setBounds(140, 120, 170, 20);

        jLabel4.setText("Admin");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 120, 80, 14);
        jPanel2.add(txtlname);
        txtlname.setBounds(510, 30, 170, 20);
        jPanel2.add(txtfname);
        txtfname.setBounds(140, 30, 170, 20);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 1140, 470);

        jButton1.setText("Add Student");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(50, 530, 150, 40);

        jLabel5.setText("Search");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 20, 60, 14);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(120, 20, 190, 20);

        jButton2.setText("jButton2");
        jPanel1.add(jButton2);
        jButton2.setBounds(330, 10, 60, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
      try{
           
            
           con = DriverManager.getConnection(url,username,password);
             st = con.createStatement();
             String sqllogmessage = "INSERT INTO tblstudentdetails (FNAME,MNAME,LNAME,AGE,CLASS,ADIMN) VALUES"
                     + " ('"+txtfname.getText()+"','"+txtmname.getText()+"','"+txtlname.getText()+"','"+txtage.getText()+"',"
                     + "'"+txtclass.getText()+"','"+txtadmin.getText()+"')";
             st.execute(sqllogmessage);
             JOptionPane.showMessageDialog(null, "<HTML><i style=\"color: green; font-size: 12px;\">Request Sent Succes</i></HTML>","School",JOptionPane.INFORMATION_MESSAGE);
       }catch(HeadlessException | SQLException ex){
   JOptionPane.showMessageDialog(null, "error"+ ex,"School",JOptionPane.INFORMATION_MESSAGE);

       }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtadmin;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtclass;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtmname;
    // End of variables declaration//GEN-END:variables
}
